---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(RColorBrewer)
library(visNetwork)

node_df <- read.csv2('node.csv', sep = ",", stringsAsFactors = FALSE)
link_df <- read.csv2('link.csv', sep = ",", stringsAsFactors = FALSE)

seed_word = 'love'
node_df %>% 
  filter(seed == seed_word) -> node_seed

link_df %>% 
  filter(seed == seed_word) -> link_seed

lapply(unique(node_seed$book), function(x){
  node_seed %>% 
    filter(book==x)->nodes
  link_seed %>% 
    filter(book==x)->links
  nodes$shape <- "dot"  
  nodes$shadow <- FALSE # Nodes will drop shadow
  nodes$title <- nodes$word # Text on click
  nodes$label <- nodes$word # Node label
  # nodes$size <- nodes$word_count# Node size
  nodes$size <- lapply(nodes$level, function(x){return (ifelse(x==0, 50,((1/x)*25)))})# Node size
  nodes$borderWidth <- 2 # Node border width
  nodes$font.size = 25
  
  # nodes$color.background <- brewer.pal(8,"Spectral")[c(1,7,8)][nodes$level+1]
  nodes$color.background <-rep(brewer.pal(8,"Spectral"),length.out=length(nodes$id))
  nodes$color.border <- "black"
  nodes$color.highlight.background <- "orange"
  nodes$color.highlight.border <- "darkred"
  
  links$length <- links$similarity
  
  return (visNetwork(nodes, links, main=x))
  
}) -> love_list
```

Row
-----------------------------------------------------------------------

### Chart A

```{r}
love_list[[1]]
```

### Chart B

```{r}
love_list[[2]]
```

### Chart C

```{r}
love_list[[3]]
```

Row
-----------------------------------------------------------------------

### Chart A

```{r}
love_list[[4]]
```

### Chart B

```{r}
love_list[[5]]
```

### Chart C

```{r}
love_list[[6]]
```

